// Problem 2
// Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
// 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
// By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

#include<stdio.h>

int generate_fibonacci(int maximum_fibonacci_value, int * array, int array_length)
{
    int *fibonacci_sequence = array;
    int x = 0;
    int last_term = 1;
    int term_before_last = 0;
    int next_fibonacci_value = 0;

    while (1)
    {
        next_fibonacci_value = last_term + term_before_last;
        if( (next_fibonacci_value > maximum_fibonacci_value) && ( x < array_length) )
        {
            break;
        }
        printf("Fibonacci = %d\r\n", next_fibonacci_value);
        fibonacci_sequence[x] = next_fibonacci_value;
        term_before_last = last_term;
        last_term = next_fibonacci_value;
        ++x;
    }

    return(x);
}


void main(void)
{
    int fibonacci_values[4098];
    int fibonacci_values_lenght = 0;
    int x = 0;
    int sum = 0;

    fibonacci_values_lenght = generate_fibonacci(4000000, fibonacci_values, 4096);
    for(x = 0; x < fibonacci_values_lenght; ++x)
    {
        if( !(fibonacci_values[x] & 0x1) )
        {
            sum += fibonacci_values[x];
        }
    }

    printf("Sum of even values is %d\r\n", sum);

}